// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVSybM65B0e7WV0HtDy3zELF8NHsbKYd8',
    appId: '1:993349408293:web:07e48560e5396d42d2d1cc',
    messagingSenderId: '993349408293',
    projectId: 'cinema-project-4eb9d',
    authDomain: 'cinema-project-4eb9d.firebaseapp.com',
    storageBucket: 'cinema-project-4eb9d.firebasestorage.app',
    measurementId: 'G-J9DN8V1KSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCbwYknt4cua843vgI15oOAbTtAa7BzlE',
    appId: '1:993349408293:android:891004641bdf4156d2d1cc',
    messagingSenderId: '993349408293',
    projectId: 'cinema-project-4eb9d',
    storageBucket: 'cinema-project-4eb9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyDNjQFoSWhgRO21eSVr8CVQF2ie-pMY',
    appId: '1:993349408293:ios:3cbf6ebcf76388a0d2d1cc',
    messagingSenderId: '993349408293',
    projectId: 'cinema-project-4eb9d',
    storageBucket: 'cinema-project-4eb9d.firebasestorage.app',
    iosBundleId: 'com.example.projectmobile.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhyDNjQFoSWhgRO21eSVr8CVQF2ie-pMY',
    appId: '1:993349408293:ios:3cbf6ebcf76388a0d2d1cc',
    messagingSenderId: '993349408293',
    projectId: 'cinema-project-4eb9d',
    storageBucket: 'cinema-project-4eb9d.firebasestorage.app',
    iosBundleId: 'com.example.projectmobile.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVSybM65B0e7WV0HtDy3zELF8NHsbKYd8',
    appId: '1:993349408293:web:e5f4c0164c675a19d2d1cc',
    messagingSenderId: '993349408293',
    projectId: 'cinema-project-4eb9d',
    authDomain: 'cinema-project-4eb9d.firebaseapp.com',
    storageBucket: 'cinema-project-4eb9d.firebasestorage.app',
    measurementId: 'G-E9YG7XXS6B',
  );

}