// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEP1ODC0JCAXP8PkEoo5pwiCyYI9u4mqQ',
    appId: '1:302307213825:web:1083cce8cf8abdd87c3600',
    messagingSenderId: '302307213825',
    projectId: 'cinema-project-b8799',
    authDomain: 'cinema-project-b8799.firebaseapp.com',
    storageBucket: 'cinema-project-b8799.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEP1ODC0JCAXP8PkEoo5pwiCyYI9u4mqQ',
    appId: '1:302307213825:android:5c59615828d9f4cd7c3600',
    messagingSenderId: '302307213825',
    projectId: 'cinema-project-b8799',
    storageBucket: 'cinema-project-b8799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEP1ODC0JCAXP8PkEoo5pwiCyYI9u4mqQ',
    appId: '1:302307213825:ios:5e5aaf7a5743fdb87c3600',
    messagingSenderId: '302307213825',
    projectId: 'cinema-project-b8799',
    storageBucket: 'cinema-project-b8799.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEP1ODC0JCAXP8PkEoo5pwiCyYI9u4mqQ',
    appId: '1:302307213825:ios:5e5aaf7a5743fdb87c3600',
    messagingSenderId: '302307213825',
    projectId: 'cinema-project-b8799',
    storageBucket: 'cinema-project-b8799.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEP1ODC0JCAXP8PkEoo5pwiCyYI9u4mqQ',
    appId: '1:302307213825:web:f477a43440ec8dd07c3600',
    messagingSenderId: '302307213825',
    projectId: 'cinema-project-b8799',
    authDomain: 'cinema-project-b8799.firebaseapp.com',
    storageBucket: 'cinema-project-b8799.appspot.com',
  );
}